export const FAILURE = 'FAILURE';
export const REQUEST_WASHROOMS = 'REQUEST_WASHROOMS';
export const RECEIVE_WASHROOMS = 'RECEIVE_WASHROOMS';
export const REQUEST_WASHROOM = 'REQUEST_WASHROOM';
export const RECEIVE_WASHROOM = 'RECEIVE_WASHROOM';
export const REQUEST_BUILDINGS = 'REQUEST_BUILDINGS';
export const RECEIVE_BUILDINGS = 'RECEIVE_BUILDINGS';
