on:
  push:
    branches:
      - auto-deploy
name: Deploy develop branch
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn build
    - name: Deploy to S3
      uses: kaskadi/action-s3cp@master
      env:
        AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_KEY_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
